export const UPDATE_CURRENT_CATEGORY = 'UPDATE_CURRENT_CATEGORY';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';


export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';

export const LOAD_COMMENTS_BY_PARENT_SUCCESS = 'LOAD_COMMENTS_BY_PARENT_SUCCESS';
